name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  upload-assets:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
          - target: aarch64-unknown-linux-gnu
          - target: aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        run: rustup update stable
        
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
          
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: vnstat-rs,vnstatd-rs
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/tags/${{ github.ref_name }}

  package:
    name: Package (deb, rpm)
    runs-on: ubuntu-latest
    needs: upload-assets
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        run: rustup update stable
        
      - name: Install packaging tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deb,cargo-generate-rpm
          
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
          
      - name: Build release binaries
        run: cargo build --release --target ${{ matrix.target }}
        
      - name: Generate DEB
        run: cargo deb --target ${{ matrix.target }} --no-build --output target/${{ matrix.target }}/debian/
          
      - name: Generate RPM
        run: cargo generate-rpm --target ${{ matrix.target }} --output target/${{ matrix.target }}/generate-rpm/
          
      - name: Upload Packages
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/${{ matrix.target }}/debian/*.deb
            target/${{ matrix.target }}/generate-rpm/*.rpm
          token: ${{ secrets.GITHUB_TOKEN }}
