name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  upload-assets:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
          - target: aarch64-unknown-linux-gnu
          - target: aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # Binaries to include in the archive.
          bin: vnstat-rs,vnstatd-rs
          # Target triple, default is host triple.
          target: ${{ matrix.target }}
          # GITHUB_TOKEN for creating a GitHub release.
          token: ${{ secrets.GITHUB_TOKEN }}
          # (Optional) On which ref to create a release.
          ref: refs/tags/${{ github.ref_name }}
